repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pycqa/pycodestyle
    rev: 2.14.0
    hooks:
      - id: pycodestyle