repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: pycodestyle
        name: pycodestyle
        entry: pycodestyle
        language: system
        types: [python]
        args: [--max-line-length=79]